upload-build-tarballs:
  executor: infrastructure_container_stable
  steps:
    - fixed_checkout
    - setup_secrets
    - upload_artifact_s3:
        bucket: << pipeline.parameters.s3_builds_bucket >>
        version: $CIRCLE_SHA1
    - when:
        condition:
          equal: [ << pipeline.parameters.master_branch >>, << pipeline.git.branch >> ]
        steps:
          - upload_artifact_s3:
              bucket: << pipeline.parameters.s3_builds_bucket >>
              version: latest
    - fail_notification

upload-release-tarballs:
  parameters:
    suffix:
      type: string
      default: ""
  executor: infrastructure_container_stable
  steps:
    - fixed_checkout
    - setup_secrets
    - upload_artifact_s3:
        bucket: << pipeline.parameters.s3_releases_bucket >>
        version: $CIRCLE_TAG
        suffix: << parameters.suffix >>
        os: ubuntu
    - upload_artifact_s3:
        bucket: << pipeline.parameters.s3_releases_bucket >>
        version: $CIRCLE_TAG
        suffix: << parameters.suffix >>
        os: macos
    - fail_notification

upload-release-tarballs-github:
  executor: infrastructure_container_stable
  steps:
    - fixed_checkout
    - setup_secrets
    - attach_workspace:
        at: << pipeline.parameters.packages_workspace >>
    - run:
        name: Upload GitHub Release Asset
        command: |
          envdir /secrets /infrastructure/scripts/upload-github-release-assets.sh \
            github_api_token=${GITHUB_API_TOKEN:?} \
            owner=${CIRCLE_PROJECT_USERNAME} \
            repo=${CIRCLE_PROJECT_REPONAME} \
            tag=<< pipeline.git.tag >> \
            ASSETS=<< pipeline.parameters.packages_workspace >>/*
    - fail_notification

publish-build-packages:
  executor: buildpack
  steps:
    - fixed_checkout
    - attach_workspace:
        at: << pipeline.parameters.packages_workspace >>
    - upload_artifacts_apt:
        packages_dir: << pipeline.parameters.packages_workspace >>
        component: testing
    - fail_notification

publish-release-packages:
  executor: buildpack
  steps:
    - fixed_checkout
    - attach_workspace:
        at: << pipeline.parameters.packages_workspace >>
    - upload_artifacts_apt:
        packages_dir: << pipeline.parameters.packages_workspace >>
        component: main
    - upload_artifacts_brew:
        packages_dir: << pipeline.parameters.packages_workspace >>
        branch: master
    - fail_notification

verify-artifacts:
  executor: infrastructure_container_stable
  steps:
    - run:
        name: Verify release artifacts
        command: |
          /infrastructure/scripts/check_release_artifacts.sh << pipeline.git.tag >>
