version: 2
build_test_deploy:
  jobs:
    - build:
        filters:
          branches:
            ignore:
              - env/dev1
              - env/dev2
              - system-tests

    - build_otp23:
        filters:
          branches:
            ignore:
              - env/dev1
              - env/dev2
              - system-tests

    - build_nix:
        filters:
          branches:
            only:
              - << pipeline.parameters.master_branch >>

    - docker_smoke_tests:
        context: ae-node-builds
        filters:
          branches:
            ignore:
              - env/dev1
              - env/dev2
              - system-tests
              - /releases\/.*/
              - << pipeline.parameters.master_branch >>

    - docker_js_sdk_smoke_test:
        context: ae-node-builds
        requires:
          - docker_smoke_tests
        filters:
          branches:
            ignore:
              - env/dev1
              - env/dev2
              - system-tests
              - /releases\/.*/
              - << pipeline.parameters.master_branch >>

    - docker_db_smoke_test:
        context: ae-node-builds
        requires:
          - docker_smoke_tests
        filters:
          branches:
            ignore:
              - env/dev1
              - env/dev2
              - system-tests
              - /releases\/.*/
              - << pipeline.parameters.master_branch >>

    - docker_system_smoke_tests:
        requires: []
        filters:
          branches:
            ignore:
              - env/dev1
              - env/dev2
              - system-tests

    - js_sdk_smoke_test:
        requires:
          - linux_package
        filters:
          branches:
            ignore:
              - env/dev1
              - env/dev2
              - system-tests

    - db_smoke_test:
        requires:
          - linux_package
        filters:
          branches:
            ignore:
              - env/dev1
              - env/dev2
              - system-tests

    - test_roma:
        requires:
          - build
        filters:
          branches:
            ignore:
              - env/dev1
              - env/dev2
              - system-tests

    - test_minerva:
        requires:
          - build
        filters:
          branches:
            ignore:
              - env/dev1
              - env/dev2
              - system-tests

    - test_fortuna:
        requires:
          - build
        filters:
          branches:
            ignore:
              - env/dev1
              - env/dev2
              - system-tests

    - test_lima:
        requires:
          - build
        filters:
          branches:
            ignore:
              - env/dev1
              - env/dev2
              - system-tests

    - test_latest:
        requires:
          - build
        filters:
          branches:
            ignore:
              - env/dev1
              - env/dev2
              - system-tests

    - test_latest_with_aesophia_compiler:
        requires:
          - build
        filters:
          branches:
            ignore:
              - env/dev1
              - env/dev2
              - system-tests

    - test_latest_otp23:
        requires:
          - build_otp23
        filters:
          branches:
            ignore:
              - env/dev1
              - env/dev2
              - system-tests

    - test_mnesia_leveled:
        requires:
          - build
        filters:
          branches:
            ignore:
              - env/dev1
              - env/dev2
              - system-tests

    - test_mnesia_rocksdb:
        requires:
          - build
        filters:
          branches:
            ignore:
              - env/dev1
              - env/dev2
              - system-tests

    - eunit_roma:
        requires:
          - build
        filters:
          branches:
            ignore:
              - env/dev1
              - env/dev2
              - system-tests
          tags:
            only: << pipeline.parameters.tag_regex >>

    - eunit_minerva:
        requires:
          - build
        filters:
          branches:
            ignore:
              - env/dev1
              - env/dev2
              - system-tests
          tags:
            only: << pipeline.parameters.tag_regex >>

    - eunit_fortuna:
        requires:
          - build
        filters:
          branches:
            ignore:
              - env/dev1
              - env/dev2
              - system-tests
          tags:
            only: << pipeline.parameters.tag_regex >>

    - eunit_lima:
        requires:
          - build
        filters:
          branches:
            ignore:
              - env/dev1
              - env/dev2
              - system-tests
          tags:
            only: << pipeline.parameters.tag_regex >>

    - eunit_latest:
        requires:
          - build
        filters:
          branches:
            ignore:
              - env/dev1
              - env/dev2
              - system-tests
          tags:
            only: << pipeline.parameters.tag_regex >>

    - aevm_tests:
        requires:
          - build
        filters:
          branches:
            ignore:
              - env/dev1
              - env/dev2
              - system-tests
          tags:
            only: << pipeline.parameters.tag_regex >>

    - docker_system_tests:
        filters:
          branches:
            only: system-tests

    - static_analysis:
        requires:
          - build
        filters:
          branches:
            ignore:
              - env/dev1
              - env/dev2
              - system-tests

    - static_analysis_otp23:
        requires:
          - build_otp23
        filters:
          branches:
            ignore:
              - env/dev1
              - env/dev2
              - system-tests

    - rebar_lock_check:
        requires:
          - build
        filters:
          branches:
            ignore:
              - env/dev1
              - env/dev2
              - system-tests

    - linux_package:
        filters:
          branches:
            ignore:
              - system-tests

    - linux_package:
        name: linux_package_bundle
        aeplugin_devmode: true
        package_kind: bundle
        filters:
          branches:
            ignore:
              - system-tests

    - ubuntu_package:
        requires: []
        filters:
          branches:
            only:
              - /releases\/.*/
              - << pipeline.parameters.master_branch >>

    - upload_build_artifacts:
        context: ae-node-builds
        requires:
          - linux_package
        filters:
          branches:
            ignore:
              - env/dev1
              - env/dev2
              - system-tests

    - osx_package:
        requires: []
        filters:
          branches:
            only:
              - /releases\/.*/
              - << pipeline.parameters.master_branch >>

    - osx_package:
        name: osx_package_bundle
        aeplugin_devmode: true
        package_kind: bundle
        filters:
          branches:
            only:
              - /releases\/.*/
              - << pipeline.parameters.master_branch >>

    - publish_build_packages:
        requires:
          - ubuntu_package
        filters:
          branches:
            only:
              - /releases\/.*/
              - << pipeline.parameters.master_branch >>

    - deploy_integration:
        context: ae-node-builds
        requires:
          - docker_db_smoke_test
          - db_smoke_test
          - test_roma
          - test_minerva
          - test_fortuna
          - test_lima
          - test_latest
          - test_latest_with_aesophia_compiler
          - test_mnesia_leveled
          - test_mnesia_rocksdb
          - eunit_roma
          - eunit_minerva
          - eunit_fortuna
          - eunit_lima
          - eunit_latest
          - aevm_tests
          - static_analysis
          - rebar_lock_check
          - linux_package
          - build_uml_diagrams
        filters:
          branches:
            only: master

    - docker_test_push_branch:
        name: docker_push_master
        context: ae-node-builds
        requires:
          - test_roma
          - test_minerva
          - test_fortuna
          - test_lima
          - test_latest
          - test_latest_with_aesophia_compiler
          - test_mnesia_leveled
          - test_mnesia_rocksdb
          - eunit_roma
          - eunit_minerva
          - eunit_fortuna
          - eunit_lima
          - eunit_latest
          - aevm_tests
          - static_analysis
          - rebar_lock_check
        filters:
          branches:
            only:
              - << pipeline.parameters.master_branch >>

    - docker_test_push_branch:
        name: docker_push_master_bundle
        context: ae-node-builds
        tag_suffix: "-bundle"
        aeplugin_devmode: true
        requires:
          - test_roma
          - test_minerva
          - test_fortuna
          - test_lima
          - test_latest
          - test_latest_with_aesophia_compiler
          - test_mnesia_leveled
          - test_mnesia_rocksdb
          - eunit_roma
          - eunit_minerva
          - eunit_fortuna
          - eunit_lima
          - eunit_latest
          - aevm_tests
          - static_analysis
          - rebar_lock_check
        filters:
          branches:
            only:
              - << pipeline.parameters.master_branch >>

    - deploy_next:
        context: ae-node-builds
        requires:
          - test_roma
          - test_minerva
          - test_fortuna
          - test_lima
          - test_latest
          - test_latest_with_aesophia_compiler
          - test_mnesia_leveled
          - test_mnesia_rocksdb
          - eunit_roma
          - eunit_minerva
          - eunit_fortuna
          - eunit_lima
          - eunit_latest
          - aevm_tests
          - static_analysis
          - rebar_lock_check
          - linux_package
        filters:
          branches:
            only: << pipeline.parameters.master_branch >>

    - deploy_dev1:
        context: ae-node-builds
        requires:
          - linux_package
        filters:
          branches:
            only: env/dev1

    - deploy_dev2:
        context: ae-node-builds
        requires:
          - linux_package
        filters:
          branches:
            only: env/dev2

    - build_uml_diagrams:
        requires:
          - build
        filters:
          branches:
            ignore:
              - env/dev1
              - env/dev2
              - system-tests

release:
  jobs:
    - linux_package:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: << pipeline.parameters.tag_regex >>

    - linux_package:
        name: linux_package_bundle
        aeplugin_devmode: true
        package_kind: bundle
        filters:
          branches:
            ignore: /.*/
          tags:
            only: << pipeline.parameters.tag_regex >>

    - ubuntu_package:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: << pipeline.parameters.tag_regex >>

    - osx_package:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: << pipeline.parameters.tag_regex >>

    - osx_package:
        name: osx_package_bundle
        aeplugin_devmode: true
        package_kind: bundle
        filters:
          branches:
            ignore: /.*/
          tags:
            only: << pipeline.parameters.tag_regex >>

    - hodl_artifact_upload:
        type: approval
        filters:
          branches:
            ignore: /.*/
          tags:
            only: << pipeline.parameters.tag_regex >>

    - upload_packages_linux:
        context: ae-node-builds
        requires:
          - linux_package
          - linux_package_bundle
          - hodl_artifact_upload
        filters:
          branches:
            ignore: /.*/
          tags:
            only: << pipeline.parameters.tag_regex >>

    - upload_packages_osx:
        context: ae-node-builds
        requires:
          - osx_package
          - osx_package_bundle
          - hodl_artifact_upload
        filters:
          branches:
            ignore: /.*/
          tags:
            only: << pipeline.parameters.tag_regex >>

    - docker_push_tag:
        context: ae-node-builds
        requires:
          - hodl_artifact_upload
        filters:
          branches:
            ignore: /.*/
          tags:
            only: << pipeline.parameters.tag_regex >>

    - docker_push_tag:
        name: docker_push_tag_bundle
        context: ae-node-builds
        tag_suffix: "-bundle"
        aeplugin_devmode: true
        requires:
          - hodl_artifact_upload
        filters:
          branches:
            ignore: /.*/
          tags:
            only: << pipeline.parameters.tag_regex >>

    - hodl_blue:
        type: approval
        filters:
          branches:
            ignore: /.*/
          tags:
            only: << pipeline.parameters.tag_regex >>

    - deploy_uat_blue:
        context: ae-node-builds
        requires:
          - linux_package
          - hodl_blue
        filters:
          branches:
            ignore: /.*/
          tags:
            only: << pipeline.parameters.tag_regex >>

    - hodl_green:
        type: approval
        filters:
          branches:
            ignore: /.*/
          tags:
            only: << pipeline.parameters.tag_regex >>

    - deploy_uat_green:
        context: ae-node-builds
        requires:
          - linux_package
          - deploy_uat_blue
          - hodl_green
        filters:
          branches:
            ignore: /.*/
          tags:
            only: << pipeline.parameters.tag_regex >>

    - hodl_latest:
        type: approval
        filters:
          branches:
            ignore: /.*/
          tags:
            only: << pipeline.parameters.tag_regex >>

    - upload_latest_packages_linux:
        context: ae-node-builds
        requires:
          - linux_package
          - hodl_latest
        filters:
          branches:
            ignore: /.*/
          tags:
            only: << pipeline.parameters.tag_regex >>

    - upload_latest_packages_osx:
        context: ae-node-builds
        requires:
          - osx_package
          - hodl_latest
        filters:
          branches:
            ignore: /.*/
          tags:
            only: << pipeline.parameters.tag_regex >>

    - publish_release_packages:
        requires:
          - linux_package
          - osx_package
          - hodl_latest
        filters:
          branches:
            ignore: /.*/
          tags:
            only: << pipeline.parameters.tag_regex >>

    - docker_push_latest:
        context: ae-node-builds
        requires:
          - docker_push_tag
          - hodl_latest
        filters:
          branches:
            ignore: /.*/
          tags:
            only: << pipeline.parameters.tag_regex >>

    - docker_push_latest:
        name: docker_push_latest_bundle
        context: ae-node-builds
        tag_suffix: "-bundle"
        aeplugin_devmode: true
        requires:
          - docker_push_tag
          - hodl_latest
        filters:
          branches:
            ignore: /.*/
          tags:
            only: << pipeline.parameters.tag_regex >>

    - verify_release_artifacts:
        context: ae-node-builds
        requires:
          - upload_packages_linux
          - upload_latest_packages_linux
          - upload_packages_osx
          - upload_latest_packages_osx
          - docker_push_tag
          - docker_push_latest
        filters:
          branches:
            ignore: /.*/
          tags:
            only: << pipeline.parameters.tag_regex >>

system_tests:
  triggers:
    - schedule:
        # run at midnight and noon UTC
        cron: "0 0,12 * * *"
        filters:
          branches:
            only:
              - << pipeline.parameters.master_branch >>
  jobs:
    - docker_system_tests
