when:
  # matches:
  #   pattern: << pipeline.parameters.tag_regex >>
  #   value: << pipeline.git.tag >>
  equal: [ refactor_ci_config, << pipeline.git.branch >> ]

jobs:
  - linux_package

  - linux_package:
      name: linux_package_bundle
      aeplugin_devmode: true
      package_kind: bundle

  - ubuntu_package

  - osx_package

  - osx_package:
      name: osx_package_bundle
      aeplugin_devmode: true
      package_kind: bundle

  - hodl_artifact_upload:
      type: approval

  - upload_packages_linux:
      context: ae-node-builds
      requires:
        - linux_package
        - linux_package_bundle
        - hodl_artifact_upload

  - upload_packages_osx:
      context: ae-node-builds
      requires:
        - osx_package
        - osx_package_bundle
        - hodl_artifact_upload

  - docker_push_tag:
      context: ae-node-builds
      requires:
        - hodl_artifact_upload

  - docker_push_tag:
      name: docker_push_tag_bundle
      context: ae-node-builds
      tag_suffix: "-bundle"
      aeplugin_devmode: true
      requires:
        - hodl_artifact_upload

  - hodl_blue:
      type: approval

  - deploy_uat_blue:
      context: ae-node-builds
      requires:
        - linux_package
        - hodl_blue

  - hodl_green:
      type: approval

  - deploy_uat_green:
      context: ae-node-builds
      requires:
        - linux_package
        - deploy_uat_blue
        - hodl_green

  - hodl_latest:
      type: approval

  - upload_latest_packages_linux:
      context: ae-node-builds
      requires:
        - linux_package
        - hodl_latest

  - upload_latest_packages_osx:
      context: ae-node-builds
      requires:
        - osx_package
        - hodl_latest

  - publish_release_packages:
      requires:
        - linux_package
        - osx_package
        - hodl_latest

  - docker_push_latest:
      context: ae-node-builds
      requires:
        - docker_push_tag
        - hodl_latest

  - docker_push_latest:
      name: docker_push_latest_bundle
      context: ae-node-builds
      tag_suffix: "-bundle"
      aeplugin_devmode: true
      requires:
        - docker_push_tag
        - hodl_latest

  - verify_release_artifacts:
      context: ae-node-builds
      requires:
        - upload_packages_linux
        - upload_latest_packages_linux
        - upload_packages_osx
        - upload_latest_packages_osx
        - docker_push_tag
        - docker_push_latest
