jobs:
  - linux-tarball:
      package_name: aeternity-$CIRCLE_TAG-ubuntu-x86_64.tar.gz
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - linux-tarball:
      name: linux-tarball-bundle
      package_name: aeternity-bundle-$CIRCLE_TAG-ubuntu-x86_64.tar.gz
      aeplugin_devmode: true
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - ubuntu_package:
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - macos-tarball:
      package_name: aeternity-$CIRCLE_TAG-macos-x86_64.tar.gz
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - macos-tarball:
      name: macos-tarball-bundle
      package_name: aeternity-bundle-$CIRCLE_TAG-macos-x86_64.tar.gz
      aeplugin_devmode: true
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - hodl_artifact_upload:
      type: approval
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - upload-tarballs-s3:
      bucket: << pipeline.parameters.s3_releases_bucket >>
      context: ae-node-builds
      requires:
        - linux-tarball
        - macos-tarball
        - linux-tarball-bundle
        - macos-tarball-bundle
        - hodl_artifact_upload
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - upload-tarballs-github-release:
      context: ae-node-builds
      requires:
        - linux-tarball
        - macos-tarball
        - linux-tarball-bundle
        - macos-tarball-bundle
        - hodl_artifact_upload
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - hodl_blue:
      type: approval
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - deploy:
      name: deploy-uat-blue
      version: $CIRCLE_TAG
      env: uat
      color: blue
      downtime: 1800 #30m
      context: ae-node-builds
      requires:
        - linux-tarball
        - hodl_blue
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - hodl_green:
      type: approval
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - deploy:
      name: deploy-uat-green
      version: $CIRCLE_TAG
      env: uat
      color: green
      downtime: 1800 #30m
      context: ae-node-builds
      requires:
        - linux-tarball
        - deploy-uat-blue
        - hodl_green
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - hodl_latest:
      type: approval
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  # - upload-release-tarballs:
  #     name: upload-latest-release-tarballs
  #     suffix: -latest
  #     context: ae-node-builds
  #     requires:
  #       - linux-tarball
  #       - macos-tarball
  #       - hodl_latest
  #     filters:
  #       branches:
  #         ignore: /.*/
  #       tags:
  #         only: << pipeline.parameters.tag_regex >>

  - publish-release-packages:
      requires:
        - linux-tarball
        - macos-tarball
        - hodl_latest
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - docker-image:
      name: docker-image-tag
      context: ae-node-builds
      image_type: tag
      requires:
        - hodl_artifact_upload
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - docker-image:
      name: docker-image-tag-bundle
      context: ae-node-builds
      aeplugin_devmode: true
      image_type: tag
      tag_suffix: -bundle
      requires:
        - hodl_artifact_upload
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - docker-image:
      name: docker-image-latest
      context: ae-node-builds
      image_type: latest
      requires:
        - docker-image-tag
        - hodl_latest
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - docker-image:
      name: docker-image-latest-bundle
      context: ae-node-builds
      aeplugin_devmode: true
      image_type: latest
      tag_suffix: -bundle
      requires:
        - docker-image-tag
        - hodl_latest
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - verify-artifacts:
      name: verify-release-artifacts
      context: ae-node-builds
      requires:
        # - upload-release-tarballs
        # - upload-latest-release-tarballs
        - upload-tarballs-s3
        - upload-tarballs-github-release
        - docker-image-tag
        - docker-image-latest
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>
