when:
  matches:
    pattern: << pipeline.parameters.tag_regex >>
    value: << pipeline.git.tag >>
jobs:
  - linux_package
  - linux_package:
      name: linux_package_bundle
      aeplugin_devmode: true
      package_kind: bundle
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - ubuntu_package:
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - osx_package:
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - osx_package:
      name: osx_package_bundle
      aeplugin_devmode: true
      package_kind: bundle
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - hodl_artifact_upload:
      type: approval
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - upload_packages_linux:
      context: ae-node-builds
      requires:
        - linux_package
        - linux_package_bundle
        - hodl_artifact_upload
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - upload_packages_osx:
      context: ae-node-builds
      requires:
        - osx_package
        - osx_package_bundle
        - hodl_artifact_upload
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - docker_push_tag:
      context: ae-node-builds
      requires:
        - hodl_artifact_upload
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - docker_push_tag:
      name: docker_push_tag_bundle
      context: ae-node-builds
      tag_suffix: "-bundle"
      aeplugin_devmode: true
      requires:
        - hodl_artifact_upload
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - hodl_blue:
      type: approval
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - deploy_uat_blue:
      context: ae-node-builds
      requires:
        - linux_package
        - hodl_blue
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - hodl_green:
      type: approval
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - deploy_uat_green:
      context: ae-node-builds
      requires:
        - linux_package
        - deploy_uat_blue
        - hodl_green
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - hodl_latest:
      type: approval
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - upload_latest_packages_linux:
      context: ae-node-builds
      requires:
        - linux_package
        - hodl_latest
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - upload_latest_packages_osx:
      context: ae-node-builds
      requires:
        - osx_package
        - hodl_latest
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - publish_release_packages:
      requires:
        - linux_package
        - osx_package
        - hodl_latest
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - docker_push_latest:
      context: ae-node-builds
      requires:
        - docker_push_tag
        - hodl_latest
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - docker_push_latest:
      name: docker_push_latest_bundle
      context: ae-node-builds
      tag_suffix: "-bundle"
      aeplugin_devmode: true
      requires:
        - docker_push_tag
        - hodl_latest
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>

  - verify_release_artifacts:
      context: ae-node-builds
      requires:
        - upload_packages_linux
        - upload_latest_packages_linux
        - upload_packages_osx
        - upload_latest_packages_osx
        - docker_push_tag
        - docker_push_latest
      filters:
        branches:
          ignore: /.*/
        tags:
          only: << pipeline.parameters.tag_regex >>
